### PR TITLE
add support for valves in context.xml

### PR DESCRIPTION
**Pull request by simonrondelez**
this solves https://tickets.puppetlabs.com/browse/MODULES-3458

### CODE REVIEW

**Comment by HelenCampbell** [comment]
Hey @simonrondelez , this PR looks great and I'm happy with the change you're trying to introduce, however when merging anything we like to ensure it's both got tests and is fully documented in the readme. Would you be able to update this PR with those changes? Thanks!

**Comment by JaminShanti** [comment]
Any updates on this?  Not being able to manage the context common_attributes is a real blocker.

**Comment by simonrondelez** [comment]
@HelenCampbell added the tests as requested

**Comment by simonrondelez** [comment]
@HelenCampbell this going to be merged or should i close my PR?

**Comment by HelenCampbell** [comment]
Hey @simonrondelez , apologies, I'm currently flat to the mat. I've asked for this PR to go in to the Tomcat work that's coming up, but I'll work with this today to see if I can sort out the failures on Travis.

**Pull request merged**
