### PR TITLE
(MODULES-5589) - add user/group to war file

### PR DESCRIPTION
**Pull request by pmcmaw**
This includes #253 with a few minor docs changes.

### CODE REVIEW

**Comment by alexjfisher** [comment]
Are you sure this actually works?

The `user` and `group` parameters of `archive` only seem to apply when `extract => true`
https://github.com/voxpupuli/puppet-archive/blob/bf4d097377c0a4f933533d0d87b03f62fac32a92/lib/puppet/type/archive.rb#L215-L221

**Comment by alexjfisher** [comment]
See https://github.com/voxpupuli/puppet-archive/issues/22

**Comment by alexjfisher** [comment]
https://github.com/puppetlabs/puppetlabs-tomcat/pull/265 has been opened as part of puppethack and *should* fix this.

**Comment by pmcmaw** [comment]
Hey @alexjfisher, thanks for the comments and apologies that the fix did not work. 
#265 Has been merged and hopefully this resolves your issue 👍

**Comment by alexjfisher** [comment]
@pmcmaw No worries.  The puppet-archive parameter names are pretty misleading.

**Pull request merged**
