### PR TITLE
add support for allow_insecure parameter.

### PR DESCRIPTION
**Pull request by lmayorga1980**

### CODE REVIEW

**Comment by lmayorga1980** [comment]
@eputnam It would be nice if you can merge this PR.

**Comment by eputnam** [comment]
hey @lmayorga1980 , thanks for the PR! could you please add some tests and add your new params to the README?

**Comment by lmayorga1980** [comment]
@eputnam , just sent a new PR with updated README and also seems like you are depending on `puppet-archive` instead of `staging`. Had to bring that change down.

**Comment by tphoney** [comment]
@eputnam this is related to ticket https://tickets.puppetlabs.com/browse/MODULES-4930

**Comment by lmayorga1980** [comment]
no needs about this PR? can it be merged?

**Comment by hunner** [comment]
I've merged the ability for `allow_insecure` in #231. The change for `copy_from_home_list` is also interesting to PR separately and is related to #218

**Pull request closed without merging**
