### PR TITLE
Feature: Add the ability to configure manager elements in context.xml

### PR DESCRIPTION
**Pull request by aaron-miller**
Adds a new defined type (tomcat::config::context::manager) which enables users to configure Manager elements in context.xml (https://tomcat.apache.org/tomcat-7.0-doc/config/manager.html). Supports adding or removing params as the users wishes.

### CODE REVIEW

**Comment by aaron-miller** [comment]
Closing and reopening to kick off another build.

**Comment by aaron-miller** [comment]
Build timed out, closing and reopening to kick off another build.

**Comment by aaron-miller** [comment]
Build keeps timing out :(

**Comment by HelenCampbell** [comment]
Hey @aaron-miller , my deepest apologies for the delay in us responding to you. The issue you are coming across is a problem on our side with the Beaker tests and will not relate to the changes you have made. Since finding this this morning we have started investigation and we will address this as soon as we can. We will review all tomcat PRs (as this affects all of them) after we have addressed the issue. Again, my apologies. We really appreciate the work you have put in to this PR.

**Comment by bmjen** [comment]
Thanks @aaron-miller !

**Comment by tphoney** [comment]
@aaron-miller great work !!!

**Pull request merged**
