### PR TITLE
MODULES-3361 Introduces user/group parameter

### PR DESCRIPTION
**Pull request by dploeger**
This fixes MODULES-3361

### CODE REVIEW

**Comment by jonnytpuppet** [comment]
Hi There

Thanks for your contribution!

In order for us to merge this, it would be appreciated if you could have a look at why the tests are failing.

Thanks

**Comment by dploeger** [comment]
I'm sorry, but like in #145 and #144 I can not find any mistake in my code, but I also can not find any real error in the test logs. Could you please have a look?

**Comment by HelenCampbell** [comment]
Hey @dploeger , my deepest apologies, we have come across an issue were the beaker tests on all tomcat PRs are timing out. This is a problem on our side and why your tests are failing. We have started investigation since we found this issue and are hoping to have it resolved as quickly as possible. We will review your PR (and your other two PRs) as soon as we have these issues addressed. Again, apologies for this, we really appreciate your effort and the work you have contributed.

**Comment by tphoney** [comment]
Apologies, i had to close then reopen this PR, to force TravisCI to pick up the reduced test run for docker. This meant that the test runs would sometimes fail through no fault of the author. The TravisCI tests now complete in 15 minutes.

**Comment by hunner** [comment]
Looks like this is merged.

**Pull request closed without merging**
