### PR TITLE
Refactor valve types

### PR DESCRIPTION
**Pull request by h-haaks**

### CODE REVIEW

**Comment by h-haaks** [comment]
@david22swan 
My second attempt to resolve MODULES-10855.
I hope you have some time to have a look at it.

**Review by david22swan — APPROVED** [review]
@h-haaks
Sorry for the wait on the review, missed the notification from Github.
Anyway overall this look's good to me and it all runs successfully against the release pipeline so I'm gonna approve it.
However due to its backwards incompatible nature I want an approve from another member of the team in order to merge it.

**Review by carabasdaniel — APPROVED** [review]
👍

**Comment by h-haaks** [comment]
Thanks @david22swan and @carabasdaniel 
Could any of you please tell me if I'm supposed to close https://tickets.puppetlabs.com/browse/MODULES-10855 my self, or if it should be looked at by someone before closing.

**Comment by h-haaks** [comment]
By the way @david22swan, why did you label this backwards-incompatible?
I don't think it is, because as my test show it's still ok to use the resource_name and resource_type params of tomcat::config::context::valve.
You'll just get a warning that tells you that it is deprecated.

**Comment by david22swan** [comment]
@h-haaks 
Yeah had labelled this wrong sorry.
Have changed it to feature and will close the ticket in a minute.
Thank's again for putting in the work.

**Pull request merged**
