### PR TITLE
support catalina_base properly

### PR DESCRIPTION
**Pull request by mrgum**
Hello

This pull will change the module in a number of ways that I required to ditch the tomcat module I rolled myself

changes are
-catalina_base is now a proper base built to use the catalina_home where the source is downloaded too
-directories under catabase_base are made
-xml files are then copied from cataina_home to catalina_base from/to the conf directory
-catalina.properties is managed as fragment and a function exists to add new name=value lines
-globalnamingresources are now defineable
-a init script for jsvc based installs is now provided

**NOTE:** users of the module still need to build jsvc and get it into the $catalina_base/bin directory

Thanks

Neil

### CODE REVIEW

**Comment by HelenCampbell** [comment]
@mrgum Thank you for your work, however there are a few things that need looked at before we review this. If you could please squash your commits and also ensure that all checks are passing we will review this in our community meeting on Thursday. Thanks.

**Comment by mrgum** [comment]
Hello.

I'll check that it passes.

For the commit squashing how would that best be done? There are something
like four features one of which requires the others. Squash it down to a
commit per feature or all in one?

Thanks,

Neil aka mrgum

**Comment by mrgum** [comment]
Hello

I've looked at the acceptance tests and they are not correct. They, like
the module does, assume that the tomcat source is extracted into catalina
base. This is not correct.

https://tomcat.apache.org/tomcat-8.0-doc/introduction.html

Catalina home is where the source should be extracted. Catalina base is for
the individual instance of tomcat, so multiple bases may use the same home.

Shall I attempt to fix the tests or might ut be better for someone else to
look at them, the current module will then fail those tests. My changes
should pass.

I think discussion and agreement on the proper use of catalina base are
required. Is that something you can do at your meeting?

Thanks

Neil

**Comment by HelenCampbell** [comment]
Hey @mrgum ,

Since this would be a rather large change the more information we have the better, so thank you for your comments :) 

Regarding the tests, I would actually hold off from doing more to this until the community review the topic itself today. You do seem to have a valid use case for this. If this feature is given the go ahead then we will have to update the tests to work with this new code and prep the pr for merge. 

Thanks,
Helen

**Comment by mrgum** [comment]
Hello

Sorry this is a bit long...

I quite agree the community review is the first thing. The principle of
separating base from home needs understanding and agreeing to.

I'm confident my use cases are valid.  Its what I do for a couple of
hundred services where I work.  CATALINA_HOME is the tomcat binaries from
apache (root owned so devs do not touch) CATALINA_BASE i owner by service
account (tomcat).

When we upgrade tomcat binaries it is only the CATALINA_HOME that is
replaced.  CATALINA_BASE remains has the logs and everything about that
instance.

Without these changes I'm stuck using self rolled tomcat module and I'd
rather move to the puppetlabs one.

The current implementation in the module does not really support
catalina_base it just uses it as another CATALINA_HOME equivalent and
leaves CATALINA_HOME empty (when catalina_base is set) that only works as
it is putting everything in CATALINA_BASE and is surely pointless?

The current module makes a bit if a mess of the catalina_base it has mixed
concerns. the software really belongs in a home, multiple homes at
different versions should be supported) and multiple bases each refering to
a particular home should be supported.

If the priciple is accepted and some assistance with writing tests is
available I'm happy to put in the time to address the functionality.

Meanwhile I'll redo my change as separate feature branches in my version
then apply as single commits to my master.  Shall I then replace my pull
request with other separate pull requests.

Thanks

Neil

**Comment by bmjen** [comment]
@mrgum Thanks for the explanations. We discussed this in our triage session and with such a large contribution and fundamental change to the module, we'll need some more time to evaluate the PR. I'll do some digging and report back.

Thanks!
Bryan

**Comment by mrgum** [comment]
Hello

Are you having another meeting tomorrow?

I'd like to know if I'd be better asking for my changes in a more piecemeal
fashion  and if you agree with the catalina home vs base split as i have
proposed

Thanks

Neil

**Pull request closed without merging**
