### PR TITLE
Implement init script

### PR DESCRIPTION
**Pull request by bodsch**
Hi Folks!

We need an init-Script to run Tomcat instances in our Production Environment.
I've implemented this one.
I tested it under CentOS 6.6 and it works for me.

I put also my hiera config into the README.md (i missed any examples ;) )

### CODE REVIEW

**Comment by igalic** [comment]
@bodsch  i'm confused as to how what you're trying to achive doesn't work with use_init right now

**Comment by bodsch** [comment]
Hi @igalic !

Sorry, i need more Information! :)

My changes put only an init-script into /etc/init.d .
I testet my changes on an CentOS 6.6 and its works perfectly (for me!).

Greetings,
 bodo

**Comment by tphoney** [comment]
@igalic can you helpe @bodsch, is there anything i can do ?

**Comment by igalic** [comment]
@tphoney i don't know.
i still don't quite understand what @bodsch's changes do that use_init doesn't

**Comment by tphoney** [comment]
@bodsch do you have further questions ?

**Comment by HelenCampbell** [comment]
Hey @bodsch, thanks for the work you have put in to this pull request. However due to inactivity and failing unit tests this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Comment by bodsch** [comment]
Hello Helen!
Sorry i'm currently bad available. :(
I think next week is better for an reply from me.

Greetings

**Comment by HelenCampbell** [comment]
No worries :)

**Comment by bodsch** [comment]
Moin Moin! :)
I found self an other bug and fix them asap.
i think in this week i have a other version and more tests

**Comment by HelenCampbell** [comment]
Tach auch!
Feel free to open another PR with any fixes and I'll have a look

**Pull request closed without merging**
