### PR TITLE
Clean up PR #76, #108, #109

### PR DESCRIPTION
**Pull request by hunner**
A lot of work was put in by @bryanjbelanger and @davideagle to enable the tomcat module to use an init script when installed from source, work with multiple instances installed in separate catalina_home directories, and fill gaps in the available resources.

This cleans up the three pull requests mentioned above and updates tests and docs.

As of yet no acceptance tests have been written.

### CODE REVIEW

**Comment by davideagle** [comment]
Thanks guys for picking up my work :)

**Comment by bmjen** [comment]
:100: :+1:

**Comment by hunner** [comment]
@davideagle I hope my changes were appropriate (I tweaked the parameters for the resource and resourcelink defines to only have parameters for required attributes and assume all others will be passed through `additional_attributes, for example).

Thanks for doing all the work on this! Sorry it took so long to get it merged.

**Comment by davideagle** [comment]
Sounds good, if I remember correctly that is the way I used the module in
the end, but it has been a while since I took a look at it but I will in
the coming weeks

**Pull request merged**
